### ISSUE TITLE
Error running from Raspbian

### ISSUE THREAD

**Issue by Grip** [bellingcat/knewkarma#31]
**Describe the bug**
Executing commands like 
`knewkarma posts --listing best`
I receive the error

```shell
04:24:44 PM Started Knew Karma 1.4.1.0 2023-11-20 16:24:44.550832...                                              knewkarma.py:18
/home/pi/test-CS/knewka/knewka/lib/python3.9/site-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/home/pi/test-CS/knewka/knewka/lib/python3.9/site-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
            Stopped in 0:00:00.368536 seconds.                                                                   knewkarma.py:110
Traceback (most recent call last):
  File "/home/pi/test-CS/knewka/knewka/bin/knewkarma", line 8, in <module>
    sys.exit(on_call())
  File "/home/pi/test-CS/knewka/knewka/lib/python3.9/site-packages/knewkarma/knewkarma.py", line 26, in on_call
    asyncio.run(api.get_updates())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/test-CS/knewka/knewka/lib/python3.9/site-packages/knewkarma/api.py", line 134, in get_updates
    notification.notify(
  File "/home/pi/test-CS/knewka/knewka/lib/python3.9/site-packages/plyer/facades/notification.py", line 84, in notify
    self._notify(
  File "/home/pi/test-CS/knewka/knewka/lib/python3.9/site-packages/plyer/facades/notification.py", line 93, in _notify
    raise NotImplementedError("No usable implementation found!")
NotImplementedError: No usable implementation found!
``` 

**To Reproduce**

1. After installing via pip
2. run `knewkarma posts --listing best`

**Expected behavior**
to receive an output containing posts from the *top* listing

**Raspberry Pi 3B+**
 - OS and Python:
  
```shell
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

python -V
Python 3.9.2

``` 
python3-dbus is already installed and I'm running it inside virtualenv.

Regards Richard!

**Comment by rly0nheart** [comment]
Hey @Grip , I noticed that error also occurs on Termux. It has got something to do with the plyer module.

Do you mind telling me the version of Knew Karma you're running? I implemented a fallback functionality in recent versions in case that error gets raised

**Comment by Grip** [comment]
Hi Richard,
I'm testing it on a Rpi without graphic environment so no popup for me ;)

anyway I did the install with the `--update` flag end that's what it does

```shell
$ pip install --upgrade knewkarma
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting knewkarma
  Using cached https://www.piwheels.org/simple/knewkarma/knewkarma-1.4.1.0-py3-none-any.whl (94 kB)
Collecting aiohttp (from knewkarma)
  Using cached aiohttp-3.9.0-cp39-cp39-linux_armv7l.whl
Collecting glyphoji (from knewkarma)
  Using cached https://www.piwheels.org/simple/glyphoji/glyphoji-0.3.1-py3-none-any.whl (44 kB)
Collecting plyer (from knewkarma)
  Using cached https://www.piwheels.org/simple/plyer/plyer-2.1.0-py3-none-any.whl (142 kB)
Collecting rich (from knewkarma)
  Using cached rich-13.7.0-py3-none-any.whl.metadata (18 kB)
Collecting attrs>=17.3.0 (from aiohttp->knewkarma)
  Using cached https://www.piwheels.org/simple/attrs/attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->knewkarma)
  Using cached https://www.piwheels.org/simple/multidict/multidict-6.0.4-cp39-cp39-linux_armv7l.whl (109 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp->knewkarma)
  Downloading yarl-1.9.3-py3-none-any.whl.metadata (28 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->knewkarma)
  Using cached https://www.piwheels.org/simple/frozenlist/frozenlist-1.4.0-cp39-cp39-linux_armv7l.whl (183 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->knewkarma)
  Using cached https://www.piwheels.org/simple/aiosignal/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout<5.0,>=4.0 (from aiohttp->knewkarma)
  Using cached https://www.piwheels.org/simple/async-timeout/async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting markdown-it-py>=2.2.0 (from rich->knewkarma)
  Using cached https://www.piwheels.org/simple/markdown-it-py/markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->knewkarma)
  Downloading pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->knewkarma)
  Using cached https://www.piwheels.org/simple/mdurl/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp->knewkarma)
  Using cached https://www.piwheels.org/simple/idna/idna-3.4-py3-none-any.whl (61 kB)
Using cached rich-13.7.0-py3-none-any.whl (240 kB)
Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.1 MB/s eta 0:00:00
Downloading yarl-1.9.3-py3-none-any.whl (30 kB)
Installing collected packages: plyer, pygments, multidict, mdurl, idna, glyphoji, frozenlist, attrs, async-timeout, yarl, markdown-it-py, aiosignal, rich, aiohttp, knewkarma
Successfully installed aiohttp-3.9.0 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 frozenlist-1.4.0 glyphoji-0.3.1 idna-3.4 knewkarma-1.4.1.0 markdown-it-py-3.0.0 mdurl-0.1.2 multidict-6.0.4 plyer-2.1.0 pygments-2.17.2 rich-13.7.0 yarl-1.9.3

``` 
and, as expected since I still have the 1.4.1.0 version, the error get raised again:

```shell
$ knewkarma -d posts --listing top

┓┏┓         ┓┏┓
┃┫ ┏┓┏┓┓┏┏  ┃┫ ┏┓┏┓┏┳┓┏┓
┛┗┛┛┗┗ ┗┻┛  ┛┗┛┗┻┛ ┛┗┗┗┻
12:07:11 PM Started Knew Karma 1.4.1.0 2023-11-23 12:07:11.090029...                           knewkarma.py:18
            Using selector: EpollSelector                                                selector_events.py:59
/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
            Stopped in 0:00:00.379240 seconds.                                                knewkarma.py:110
Traceback (most recent call last):
  File "/home/pi/test-CS/kewka/knewka/bin/knewkarma", line 8, in <module>
    sys.exit(on_call())
  File "/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/knewkarma/knewkarma.py", line 26, in on_call
    asyncio.run(api.get_updates())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/knewkarma/api.py", line 134, in get_updates
    notification.notify(
  File "/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/plyer/facades/notification.py", line 84, in notify
    self._notify(
  File "/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/plyer/facades/notification.py", line 93, in _notify
    raise NotImplementedError("No usable implementation found!")
NotImplementedError: No usable implementation found!

``` 

what can I do to install the updated version?

Regards

**Comment by rly0nheart** [comment]
Alright, I've identified the error. I'm going to push a patch in a few minutes then I will let you know and also ask you to test it

**Comment by rly0nheart** [comment]
@Grip the release has been published

**Comment by Grip** [comment]
hi,
installing in virtualenv:

```shell
 $ pip cache purge
Files removed: 1338

$ pip install --upgrade knewkarma
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting knewkarma
  Downloading https://www.piwheels.org/simple/knewkarma/knewkarma-1.4.1.0-py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.3/94.3 kB 943.2 kB/s eta 0:00:00
Collecting aiohttp (from knewkarma)
  Downloading aiohttp-3.9.0.tar.gz (7.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 3.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting glyphoji (from knewkarma)
  Downloading https://www.piwheels.org/simple/glyphoji/glyphoji-0.3.1-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 563.2 kB/s eta 0:00:00
Collecting plyer (from knewkarma)
  Downloading https://www.piwheels.org/simple/plyer/plyer-2.1.0-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.3/142.3 kB 1.6 MB/s eta 0:00:00
Collecting rich (from knewkarma)
  Downloading rich-13.7.0-py3-none-any.whl.metadata (18 kB)
Collecting attrs>=17.3.0 (from aiohttp->knewkarma)
  Downloading https://www.piwheels.org/simple/attrs/attrs-23.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 689.8 kB/s eta 0:00:00
Collecting multidict<7.0,>=4.5 (from aiohttp->knewkarma)
  Downloading https://www.piwheels.org/simple/multidict/multidict-6.0.4-cp39-cp39-linux_armv7l.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.1/109.1 kB 869.5 kB/s eta 0:00:00
Collecting yarl<2.0,>=1.0 (from aiohttp->knewkarma)
  Downloading yarl-1.9.3-py3-none-any.whl.metadata (28 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->knewkarma)
  Downloading https://www.piwheels.org/simple/frozenlist/frozenlist-1.4.0-cp39-cp39-linux_armv7l.whl (183 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.3/183.3 kB 1.3 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2 (from aiohttp->knewkarma)
  Downloading https://www.piwheels.org/simple/aiosignal/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout<5.0,>=4.0 (from aiohttp->knewkarma)
  Downloading https://www.piwheels.org/simple/async-timeout/async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting markdown-it-py>=2.2.0 (from rich->knewkarma)
  Downloading https://www.piwheels.org/simple/markdown-it-py/markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 1.3 MB/s eta 0:00:00
Collecting pygments<3.0.0,>=2.13.0 (from rich->knewkarma)
  Downloading pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->knewkarma)
  Downloading https://www.piwheels.org/simple/mdurl/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp->knewkarma)
  Downloading https://www.piwheels.org/simple/idna/idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 701.6 kB/s eta 0:00:00
Downloading rich-13.7.0-py3-none-any.whl (240 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.6/240.6 kB 2.7 MB/s eta 0:00:00
Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.0 MB/s eta 0:00:00
Downloading yarl-1.9.3-py3-none-any.whl (30 kB)
Building wheels for collected packages: aiohttp
  Building wheel for aiohttp (pyproject.toml) ... done
  Created wheel for aiohttp: filename=aiohttp-3.9.0-cp39-cp39-linux_armv7l.whl size=1119851 sha256=757d4b220fbb5ea2d97c30df18f93f5964858d0993d5a9fb987082bba945611c
  Stored in directory: /home/pi/.cache/pip/wheels/c7/de/d2/382b6b59b8fd35a4a8a01f90a09a81aaa26cee25056c755dfe
Successfully built aiohttp
Installing collected packages: plyer, pygments, multidict, mdurl, idna, glyphoji, frozenlist, attrs, async-timeout, yarl, markdown-it-py, aiosignal, rich, aiohttp, knewkarma
Successfully installed aiohttp-3.9.0 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 frozenlist-1.4.0 glyphoji-0.3.1 idna-3.4 knewkarma-1.4.1.0 markdown-it-py-3.0.0 mdurl-0.1.2 multidict-6.0.4 plyer-2.1.0 pygments-2.17.2 rich-13.7.0 yarl-1.9.3

$ knewkarma -v
1.4.1.0

``` 

and sure enough

```shell
$ knewkarma search "covid"

┓┏┓         ┓┏┓
┃┫ ┏┓┏┓┓┏┏  ┃┫ ┏┓┏┓┏┳┓┏┓
┛┗┛┛┗┗ ┗┻┛  ┛┗┛┗┻┛ ┛┗┗┗┻
03:24:58 PM Started Knew Karma 1.4.1.0 2023-11-23 15:24:58.435412...                                                  knewkarma.py:18
/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
            Stopped in 0:00:00.354330 seconds.                                                                       knewkarma.py:110
Traceback (most recent call last):
  File "/home/pi/test-CS/kewka/knewka/bin/knewkarma", line 8, in <module>
    sys.exit(on_call())
  File "/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/knewkarma/knewkarma.py", line 26, in on_call
    asyncio.run(api.get_updates())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/knewkarma/api.py", line 134, in get_updates
    notification.notify(
  File "/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/plyer/facades/notification.py", line 84, in notify
    self._notify(
  File "/home/pi/test-CS/kewka/knewka/lib/python3.9/site-packages/plyer/facades/notification.py", line 93, in _notify
    raise NotImplementedError("No usable implementation found!")
NotImplementedError: No usable implementation found!

```

better installing with Docker, now it works as expected but if I try one of the examples in the wiki:

```shell
-d posts --listing top
Usage: knewkarma posts [-h] [-f] [-l {all,best,controversial,popular,rising}]
knewkarma posts: error: argument -l/--listing: invalid choice: 'top' (choose from 'all', 'best', 'controversial', 'popular', 'rising')

``` 
 
is it something I've not understood on the workings or is just the wiki that needs a "refresh"?

Thank you Richard!!

**Comment by rly0nheart** [comment]
In that output, it shows you're running version 1.4 (which has got more bugs than the latest release)

I have publish a patch that fixes the errors you're getting in that version. run `pip install --upgrade knewkarma` to upgrade to the latest 2.3.1.0

**Comment by Grip** [comment]
You were almost entirely right: by what I see on piwheels.org page it seems that version 2.0.0.0 is ready to ship (build succeeded) but I still can install just 1.4.10.
The reason is that on my Rpi Bullseye I just have Python 3.9.2 while recent packages of knewkarma all requires python 3.10 minimum...

```shell
pip install knewkarma==2.0.0.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Ignored the following versions that require a different python version: 1.5.0.0 Requires-Python >=3.10,<4.0; 1.5.1.0 Requires-Python >=3.10,<4.0; 1.5.2.0 Requires-Python >=3.10,<4.0; 1.6.0.0 Requires-Python >=3.10,<4.0; 2.0.0.0 Requires-Python >=3.10,<4.0; 2.0.0.0b1 Requires-Python >=3.10,<4.0; 2.1.0.0 Requires-Python >=3.10,<4.0; 2.2.0.0 Requires-Python >=3.10,<4.0; 2.3.0.0 Requires-Python >=3.10,<4.0; 2.3.1.0 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement knewkarma==2.0.0.0 (from versions: 1.0.0.0, 1.1.0.0, 1.2.0.0, 1.3.0.0, 1.4.0.0, 1.4.1.0)
ERROR: No matching distribution found for knewkarma==2.0.0.0
```  

That also explains why I have no more problems on Docker: it installs the latest version of Knewkarma since it has the latest version (3.12) of Python..

It's time for me to install Python from sources I suppose...

**Comment by rly0nheart** [comment]
> You were almost entirely right: by what I see on piwheels.org page it seems that version 2.0.0.0 is ready to ship (build succeeded) but I still can install just 1.4.10.
> The reason is that on my Rpi Bullseye I just have Python 3.9.2 while recent packages of knewkarma all requires python 3.10 minimum...
> 
> ```shell
> pip install knewkarma==2.0.0.0
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> ERROR: Ignored the following versions that require a different python version: 1.5.0.0 Requires-Python >=3.10,<4.0; 1.5.1.0 Requires-Python >=3.10,<4.0; 1.5.2.0 Requires-Python >=3.10,<4.0; 1.6.0.0 Requires-Python >=3.10,<4.0; 2.0.0.0 Requires-Python >=3.10,<4.0; 2.0.0.0b1 Requires-Python >=3.10,<4.0; 2.1.0.0 Requires-Python >=3.10,<4.0; 2.2.0.0 Requires-Python >=3.10,<4.0; 2.3.0.0 Requires-Python >=3.10,<4.0; 2.3.1.0 Requires-Python >=3.10,<4.0
> ERROR: Could not find a version that satisfies the requirement knewkarma==2.0.0.0 (from versions: 1.0.0.0, 1.1.0.0, 1.2.0.0, 1.3.0.0, 1.4.0.0, 1.4.1.0)
> ERROR: No matching distribution found for knewkarma==2.0.0.0
> ```  
> 
> That also explains why I have no more problems on Docker: it installs the latest version of Knewkarma since it has the latest version (3.12) of Python..
> 
> It's time for me to install Python from sources I suppose...

ah that makes sense😅. But I think it's work celebrating if it works just fine as docker container🕺🏾
